version: "3.8"

name: chatter

services:
  postgres:
    image: postgres
    restart: always

    volumes:
      - postgres-data:/var/lib/postgresql/data

    ports:
      - "${VITE_DB_FORWARD_PORT:-5432}:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: ${VITE_DB_USER:-chatter}
      POSTGRES_PASSWORD: ${VITE_DB_PASSWORD:-chatter}
      POSTGRES_DB: ${VITE_DB_DATABASE:-chatter}

  postgres-dev:
    image: postgres
    restart: always

    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: ${VITE_DB_USER:-chatter}
      POSTGRES_PASSWORD: ${VITE_DB_PASSWORD:-chatter}
      POSTGRES_DB: ${VITE_DB_DATABASE:-chatter}

volumes:
  postgres-data:
  postgres-dev-data:
  pgadmin-data:
