version: "3.7"

services:
  chatter-app:
    build:
      dockerfile: Dockerfile

    ports:
      - "${APP_PORT:-3000}:3000"

  mariadb:
    image: mariadb:10.11
    restart: always

    volumes:
      - mariadb-data:/var/lib/mysql

    ports:
      - "${MYSQL_FORWARD_PORT:-3306}:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER:-chatter}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-chatter}

volumes:
  mariadb-data:
