version: "3.7"

services:
  chatter-app:
    build:
      dockerfile: Dockerfile

    ports:
      - "${APP_PORT:-3000}:3000"

  mariadb:
    image: mariadb:10.11
    restart: always

    volumes:
      - mariadb-data:/var/lib/mysql

    ports:
      - "${VITE_DB_FORWARD_PORT:-3306}:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${VITE_DB_USER:-chatter}
      MARIADB_PASSWORD: ${VITE_DB_PASSWORD}
      MYSQL_DATABASE: ${VITE_DB_DATABASE:-chatter}

volumes:
  mariadb-data:
